name: blank
on:
  push:
jobs:
  blank:
    runs-on: ubuntu-latest
    steps:
      - name: MyCommands
        run: |
          hostname -i
          hostname -I
          ifconfig
          ip -4 -br addr
